server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true

        multipart:
            enabled: true
    servlet:
        multipart:
            max-file-size: 8MB
            max-request-size: 8MB
    datasource:
        url: jdbc:mysql://localhost:3306/annex
        username: root
        password: n7B37b**#un83
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    #mail:
    #    host: localhost
    #    port: 1025
    #    username: hello
    #    password: hello
    #
    #properties:
    #    mail:
    #        smtp:
    #            ssl:
    #                trust: "*"
    #            auth: true
    #            starttls:
    #                enable: true
    #                required: true
    #            connectiontimeout: 5000
    #            timeout: 3000
    #            writetimeout: 5000

rsa:
    private-key: "classpath:certs/private.pem"
    public-key: "classpath:certs/public.pem"

jwt:
    expiration:
        time: 900000